on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: CodePass
          path: out

  document:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i
      - run: npm run document
      - uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: docs
      - uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'docs'
          destination_repo: 'mygizli04/mygizli04.github.io'
          destination_folder: 'CodePass'
          user_email: 'mygizli04@gmail.com'
          user_name: 'mygizli04'